# Generated by Django 3.0.5 on 2020-04-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200409_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza_size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza_topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza_topping_combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_add_on',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping',
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('add_ons', models.ManyToManyField(blank=True, to='orders.Sub_add_on')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Sub_name')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Sub_size')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='combo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.Pizza_topping_combo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.Pizza_topping'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Pizza_size'),
        ),
    ]
