# Generated by Django 3.0.5 on 2020-06-10 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200524_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dinner_platters',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pastas',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizzas',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subs',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='Pizza_order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='orders.Order')),
                ('pizza', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Pizza')),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Pizza_topping')),
            ],
        ),
    ]
