# Generated by Django 3.0.5 on 2020-06-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200610_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza_topping_combo',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
