# Generated by Django 3.0.5 on 2020-07-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200708_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_add_on',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
