# Generated by Django 3.0.5 on 2020-07-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_sub_order_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salad_order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salads', to='orders.Order')),
                ('salad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Salad')),
            ],
        ),
        migrations.CreateModel(
            name='Pasta_order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to='orders.Order')),
                ('pasta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Pasta')),
            ],
        ),
        migrations.CreateModel(
            name='Dinner_platter_order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('dinner_platter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Dinner_platter')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_platters', to='orders.Order')),
            ],
        ),
    ]
