# Generated by Django 3.0.5 on 2020-07-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_dinner_platter_order_item_pasta_order_item_salad_order_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza_name',
            new_name='PizzaName',
        ),
        migrations.RenameModel(
            old_name='Pizza_size',
            new_name='PizzaSize',
        ),
        migrations.RenameModel(
            old_name='Pizza_topping',
            new_name='PizzaTopping',
        ),
        migrations.RenameModel(
            old_name='Pizza_topping_combo',
            new_name='PizzaToppingCombo',
        ),
        migrations.RenameModel(
            old_name='Sub_name',
            new_name='SubName',
        ),
    ]
