# Generated by Django 3.0.5 on 2020-07-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200720_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_size',
            new_name='SubSize',
        ),
    ]
