# Generated by Django 3.0.5 on 2020-07-20 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200720_1751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dinner_platter',
            new_name='DinnerPlatter',
        ),
        migrations.RenameModel(
            old_name='Dinner_platter_name',
            new_name='DinnerPlatterName',
        ),
        migrations.RenameModel(
            old_name='Dinner_platter_order_item',
            new_name='DinnerPlatterOrderItem',
        ),
        migrations.RenameModel(
            old_name='Dinner_platter_size',
            new_name='DinnerPlatterSize',
        ),
        migrations.RenameModel(
            old_name='Order_status',
            new_name='OrderStatus',
        ),
        migrations.RenameModel(
            old_name='Pasta_order_item',
            new_name='PastaOrderItem',
        ),
        migrations.RenameModel(
            old_name='Pizza_order_item',
            new_name='PizzaOrderItem',
        ),
        migrations.RenameModel(
            old_name='Salad_order_item',
            new_name='SaladOrderItem',
        ),
        migrations.RenameModel(
            old_name='Sub_add_on',
            new_name='SubAddOn',
        ),
        migrations.RenameModel(
            old_name='Sub_order_item',
            new_name='SubOrderItem',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='add_ons',
        ),
    ]
